databases:
  - name: expenser-database
    databaseName: expenser_database
    user: expenser_database_user

services:
  - type: web
    name: expense-track
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expenser-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false